# Файл содержит спискок всех фич с описанием типа

features = {
    "train.csv": {
        "year": (("numeric", None), ("categorical", None)),
        "station_id": (("categorical", None),),
        "day": (("numeric", None), ("categorical", None)),
        "ice_jam": (("numeric", None),),
    },
    "hydro_1day.csv": {
        "year": (("numeric", None), ("categorical", None)),
        "station_id": (("categorical", None),),
        "month": (("numeric", None), ("categorical", None)),
        "day": (("numeric", None), ("categorical", None)),
        "date": (("date", None),),
        "stage_avg": (("numeric", None),),
        "stage_min": (("numeric", None),),
        "stage_max": (("numeric", None),),
        "temp": (("numeric", None),),
        "water_code": (("water_codes", None),),
        "ice_thickness": (("numeric", None),),
        "snow_height": (("numeric", None),),
        "place": (("categorical", None),),
        "discharge": (("numeric", None),),
    },
    "meteo_1day.csv": {
        "station_id": (("categorical", None),),
        "year": (("numeric", None), ("categorical", None)),
        "month": (("numeric", None), ("categorical", None)),
        "day": (("numeric", None), ("categorical", None)),
        "route_type": (("categorical", None),),
        "snow_coverage_near_station": (("numeric", None),),
        "snow_coverage_route": (("numeric", None),),
        "ice_crust_route": (("numeric", None),),
        "snow_height_aver": (("numeric", None),),
        "snow_height_max": (("numeric", None),),
        "snow_height_min": (("numeric", None),),
        "snow_density_aver": (("numeric", None),),
        "ice_crust_aver": (("numeric", None),),
        "snow_saturated_thickness": (("numeric", None),),
        "water_thickness": (("numeric", None),),
        "water_in_snow": (("numeric", None),),
        "water_total": (("numeric", None),),
        "snow_coverage_charact": (("categorical", None),),
        "snow_charact": (("categorical", None),),
        "snow_height": (("numeric", 9999),),
        "snow_coverage_station": (("numeric", None),),
        "snow_height_q1": (("categorical", None),),
        "snow_height_q2": (("categorical", None),),
        "snow_height_q3": (("categorical", None),),
        "temperature_20cm": (("numeric", 9999),),
        "temperature_20cm_qual": (("categorical", None),),
        "temperature_40cm": (("numeric", 9999),),
        "temperature_40cm_qual": (("categorical", None),),
        "temperature_80cm": (("numeric", 9999),),
        "temperature_80cm_qual": (("categorical", None),),
        "temperature_120cm": (("numeric", 9999),),
        "temperature_120cm_qual": (("categorical", None),),
        "temperature_160cm": (("numeric", 9999),),
        "temperature_160cm_qual": (("categorical", None),),
        "temperature_240cm": (("numeric", 9999),),
        "temperature_240cm_qual": (("categorical", None),),
        "temperature_320cm": (("numeric", 9999),),
        "temperature_320cm_qual": (("categorical", None),),
        "temperature_ks_5cm": (("numeric", 9999),),
        "temperature_ks_5cm_qual": (("categorical", None),),
        "temperature_ks_10cm": (("numeric", 9999),),
        "temperature_ks_10cm_qual": (("categorical", None),),
        "temperature_ks_15cm": (("numeric", 9999),),
        "temperature_ks_15cm_qual": (("categorical", None),),
        "temperature_ks_20cm": (("numeric", 9999),),
        "temperature_ks_20cm_qual": (("categorical", None),),
        "date": (("date", None),),
        "target_year": (("drop", None),),
    },
    "hydro_coord.csv": {
        "station_id": (("categorical", None),),
        "name": (("drop", None),),
        "lat": (("numeric", None),),
        "lon": (("numeric", None),),
        "distance_from_source": (("numeric", None),),
        "drainage_area": (("numeric", None),),
        "z_null": (("numeric", None),),
    },
    "meteo_coord.csv": {
        "station_id": (("categorical", None),),
        "name": (("drop", None),),
        "lat": (("numeric", None),),
        "lon": (("numeric", None),),
        "z": (("numeric", None),),
    },
}

flow_graph_int = {
    3019: 3021,
    3087: 3021,
    3021: 3024,
    3024: 3554,
    3554: 3027,
    3106: 3555,
    3555: 3028,
    3027: 3028,
    3028: 3029,
    3029: 3030,
    3030: 3031,
    3031: 3032,
    3032: 3035,
    3035: 3036,
    3180: 3036,
    3169: 3036,
    3036: 3037,
    3037: 3038,
    3038: 3041,
    3041: 3042,
    3042: 3045,
    3045: 3047,
    3047: 3048,
    3048: 3230,
    3229: 3230,
    3230: 3050,
}

back_flow_graph_known = {
    3087: 0,
    3019: 0,
    3021: 0,
    3024: 0,
    3554: 0,
    3027: 0,
    3106: 0,
    3555: 0,
    3028: 3027,
    3029: 3028,
    3030: 3029,
    3031: 3030,
    3032: 3030,
    3035: 3030,
    3180: 0,
    3036: 3035,
    3169: 0,
    3037: 3035,
    3038: 3035,
    3041: 3035,
    3042: 3041,
    3045: 3041,
    3047: 3045,
    3048: 3045,
    3229: 0,
    3230: 3045,
    3050: 3230,
}
