# Файл содержит спискок всех фич с описанием типа

features = {
    "train.csv": {
        "year": (("numeric", None), ("categorical", None)),
        "station_id": (("categorical", None),),
        "day": (("numeric", None), ("categorical", None)),
        "ice_jam": (("numeric", None),),
    },
    "hydro_1day.csv": {
        "year": (("numeric", None), ("categorical", None)),
        "station_id": (("categorical", None),),
        "month": (("numeric", None), ("categorical", None)),
        "day": (("numeric", None), ("categorical", None)),
        "date": (("date", None),),
        "stage_avg": (("numeric", None),),
        "stage_min": (("numeric", None),),
        "stage_max": (("numeric", None),),
        "temp": (("numeric", None),),
        "water_code": (("water_codes", None),),
        "ice_thickness": (("numeric", None),),
        "snow_height": (("numeric", None),),
        "place": (("categorical", None),),
        "discharge": (("numeric", None),),
    },
    "meteo_1day.csv": {
        "station_id": (("categorical", None),),
        "year": (("numeric", None), ("categorical", None)),
        "month": (("numeric", None), ("categorical", None)),
        "day": (("numeric", None), ("categorical", None)),
        "route_type": (("categorical", None),),
        "snow_coverage_near_station": (("numeric", None),),
        "snow_coverage_route": (("numeric", None),),
        "ice_crust_route": (("numeric", None),),
        "snow_height_aver": (("numeric", None),),
        "snow_height_max": (("numeric", None),),
        "snow_height_min": (("numeric", None),),
        "snow_density_aver": (("numeric", None),),
        "ice_crust_aver": (("numeric", None),),
        "snow_saturated_thickness": (("numeric", None),),
        "water_thickness": (("numeric", None),),
        "water_in_snow": (("numeric", None),),
        "water_total": (("numeric", None),),
        "snow_coverage_charact": (("categorical", None),),
        "snow_charact": (("categorical", None),),
        "snow_height": (("numeric", 9999),),
        "snow_coverage_station": (("numeric", None),),
        "snow_height_q1": (("categorical", None),),
        "snow_height_q2": (("categorical", None),),
        "snow_height_q3": (("categorical", None),),
        "temperature_20cm": (("numeric", 9999),),
        "temperature_20cm_qual": (("categorical", None),),
        "temperature_40cm": (("numeric", 9999),),
        "temperature_40cm_qual": (("categorical", None),),
        "temperature_80cm": (("numeric", 9999),),
        "temperature_80cm_qual": (("categorical", None),),
        "temperature_120cm": (("numeric", 9999),),
        "temperature_120cm_qual": (("categorical", None),),
        "temperature_160cm": (("numeric", 9999),),
        "temperature_160cm_qual": (("categorical", None),),
        "temperature_240cm": (("numeric", 9999),),
        "temperature_240cm_qual": (("categorical", None),),
        "temperature_320cm": (("numeric", 9999),),
        "temperature_320cm_qual": (("categorical", None),),
        "temperature_ks_5cm": (("numeric", 9999),),
        "temperature_ks_5cm_qual": (("categorical", None),),
        "temperature_ks_10cm": (("numeric", 9999),),
        "temperature_ks_10cm_qual": (("categorical", None),),
        "temperature_ks_15cm": (("numeric", 9999),),
        "temperature_ks_15cm_qual": (("categorical", None),),
        "temperature_ks_20cm": (("numeric", 9999),),
        "temperature_ks_20cm_qual": (("categorical", None),),
        "date": (("date", None),),
        "target_year": (("drop", None),),
    },
    "hydro_coord.csv": {
        "station_id": (("categorical", None),),
        "name": (("drop", None),),
        "lat": (("numeric", None),),
        "lon": (("numeric", None),),
        "distance_from_source": (("numeric", None),),
        "drainage_area": (("numeric", None),),
        "z_null": (("numeric", None),),
    },
    "meteo_coord.csv": {
        "station_id": (("categorical", None),),
        "name": (("drop", None),),
        "lat": (("numeric", None),),
        "lon": (("numeric", None),),
        "z": (("numeric", None),),
    },
    "meteo_3hours.csv": {
        "station_id": (("categorical", None),),
        "year_GMT": (("drop", None),),
        "month_GMT": (("drop", None),),
        "day_GMT": (("drop", None),),
        "synop_hour_GMT": (("drop", None),),
        "year_local": (("numeric", None), ("categorical", None)),
        "month_local": (("numeric", None), ("categorical", None)),
        "day_local": (("numeric", None), ("categorical", None)),
        "synop_hour_local": (("numeric", None), ("categorical", None)),
        "synop_hour_order_PDZV": (("drop", None),),
        "time_local": (("drop", None),),
        "timezone": (("drop", None),),
        "meteo_day_start_PDZV": (("drop", None),),
        "source_index": (("drop", None),),
        "horizontal_visibility": (("categorical", None),),
        "horizontal_visibility_qual": (("categorical", None),),
        "horizontal_visibility_qual_1": (("categorical", None),),
        "cloud_amount_total": (("categorical", None),),
        "cloud_amount_total_qual": (("categorical", None),),
        "cloud_amount_low_level": (("categorical", None),),
        "cloud_amount_low_level_qual": (("categorical", None),),
        "cloud_form_high_level": (("categorical", None),),
        "cloud_form_high_level_qual": (("categorical", None),),
        "cloud_form_middle_level": (("categorical", None),),
        "cloud_form_middle_level_qual": (("categorical", None),),
        "cloud_form_vertical_develop": (("categorical", None),),
        "cloud_form_vertical_develop_qual": (("categorical", None),),
        "cloud_form_strat_stratocum": (("categorical", None),),
        "cloud_form_strat_stratocum_qual": (("categorical", None),),
        "cloud_form_strat_rain": (("categorical", None),),
        "cloud_form_strat_rain_qual": (("categorical", None),),
        "cloud_base_altitude": (("categorical", None),),
        "cloud_base_altitude_qual": (("categorical", None),),
        "cloud_base_altitude_qual_1": (("categorical", None),),
        "cloud_below_station": (("categorical", None),),
        "cloud_below_station_qual": (("categorical", None),),
        "soil_surface_condition": (("categorical", None),),
        "soil_surface_condition_qual": (("categorical", None),),
        "weather_before": (("categorical", None),),
        "weather_before_qual": (("categorical", None),),
        "weather": (("categorical", None),),
        "weather_qual": (("categorical", None),),
        "wind_direction": (("numeric", None),),
        "wind_direction_qual": (("categorical", None),),
        "wind_speed_aver": (("numeric", None),),
        "wind_speed_aver_qual": (("categorical", None),),
        "wind_speed_aver_qual_1": (("categorical", None),),
        "wind_speed_max": (("numeric", None),),
        "wind_speed_max_qual": (("categorical", None),),
        "wind_speed_max_qual_1": (("categorical", None),),
        "precipitation": (("numeric", None),),
        "precipitation_qual": (("categorical", None),),
        "soil_surface_temperature": (("numeric", None),),
        "soil_surface_temperature_qual": (("categorical", None),),
        "soil_surface_alco_temperature": (("numeric", None),),
        "soil_surface_alco_temperature_qual": (("categorical", None),),
        "soil_surface_temperature_min_before": (("numeric", None),),
        "soil_surface_temperature_min_before_qual": (("categorical", None),),
        "soil_surface_temperature_max_before": (("numeric", None),),
        "soil_surface_temperature_max_before_qual": (("categorical", None),),
        "soil_surface_max_temperature": (("numeric", None),),
        "soil_surface_max_temperature_qual": (("categorical", None),),
        "air_temperature": (("numeric", None),),
        "air_temperature_qual": (("categorical", None),),
        "air_temperature_wet_bulb": (("numeric", None),),
        "air_temperature_wet_bulb_qual": (("categorical", None),),
        "air_temperature_wet_bulb_qual_1": (("categorical", None),),
        "air_temperature_min_alco_temperature": (("numeric", None),),
        "air_temperature_min_alco_temperature_qual": (("categorical", None),),
        "air_temperature_min_before": (("numeric", None),),
        "air_temperature_min_before_qual": (("categorical", None),),
        "air_temperature_max_before": (("numeric", None),),
        "air_temperature_max_before_qual": (("categorical", None),),
        "air_max_temperature": (("numeric", None),),
        "air_max_temperature_qual": (("categorical", None),),
        "water_vapour_partial_pressure": (("numeric", None),),
        "water_vapour_partial_pressure_qual": (("categorical", None),),
        "water_vapour_partial_pressure_qual_1": (("categorical", None),),
        "relative_humidity": (("numeric", None),),
        "relative_humidity_qual": (("categorical", None),),
        "vapour_pressure_deficit": (("numeric", None),),
        "vapour_pressure_deficit_qual": (("categorical", None),),
        "vapour_pressure_deficit_qual_1": (("categorical", None),),
        "dew_point_temperature": (("numeric", None),),
        "dew_point_temperature_qual": (("categorical", None),),
        "pressure": (("numeric", None),),
        "pressure_qual": (("categorical", None),),
        "pressure_sea_level": (("numeric", None),),
        "pressure_sea_level_qual": (("categorical", None),),
        "barometric_tendency_characteristic": (("categorical", None),),
        "barometric_tendency_characteristic_qual": (("categorical", None),),
        "barometric_tendency": (("numeric", None),),
        "barometric_tendency_qual": (("categorical", None),),
        "date_local": (("drop", None),),
    },
}

flow_graph_int = {
    3019: 3021,
    3087: 3021,
    3021: 3024,
    3024: 3554,
    3554: 3027,
    3106: 3555,
    3555: 3028,
    3027: 3028,
    3028: 3029,
    3029: 3030,
    3030: 3031,
    3031: 3032,
    3032: 3035,
    3035: 3036,
    3180: 3036,
    3169: 3036,
    3036: 3037,
    3037: 3038,
    3038: 3041,
    3041: 3042,
    3042: 3045,
    3045: 3047,
    3047: 3048,
    3048: 3230,
    3229: 3230,
    3230: 3050,
}

back_flow_graph_known = {
    3087: 0,
    3019: 0,
    3021: 0,
    3024: 0,
    3554: 0,
    3027: 0,
    3106: 0,
    3555: 0,
    3028: 3027,
    3029: 3028,
    3030: 3029,
    3031: 3030,
    3032: 3030,
    3035: 3030,
    3180: 0,
    3036: 3035,
    3169: 0,
    3037: 3035,
    3038: 3035,
    3041: 3035,
    3042: 3041,
    3045: 3041,
    3047: 3045,
    3048: 3045,
    3229: 0,
    3230: 3045,
    3050: 3230,
}
